### PR TITLE
added WaitingList, QRCodeList, and FacilityList classes

### PR DESCRIPTION
**Pull request by EricWang1117**

### CODE REVIEW

**Comment by PinguinoF78** [comment]
For Lottery.java, it's supposed to handle "Send notifications to entrants of their lottery outcome" and "Handle re-selection when an invitation is declined" too, no? I was also doing Lottery.java since I didn't know you were working on it, and I implemented those responsibilities mentioned in the CRC cards.

**Comment by EricWang1117** [comment]
> For Lottery.java, it's supposed to handle "Send notifications to entrants of their lottery outcome" and "Handle re-selection when an invitation is declined" too, no? I was also doing Lottery.java since I didn't know you were working on it, and I implemented those responsibilities mentioned in the CRC cards.

Oh sorry I was going to implement the rest of the features afterwards. Since you're already done we'll use your implementation.

**Comment by PinguinoF78** [comment]
I can add my Lottery.java but idk if it'll cause problems when trying to merge, but I'll make the request and you and Nathan can both check it over to see if you think it's correct or not

**Comment by PinguinoF78** [comment]
For your WaitingList.java, where do you handle "Support querying for entrant details", which is mentioned in the CRC card?

**Comment by EricWang1117** [comment]
> For your WaitingList.java, where do you handle "Support querying for entrant details", which is mentioned in the CRC card?

I've edited the file

**Comment by PinguinoF78** [comment]
I think the querying looks good, but let's wait to see what Nathan thinks.

**Review by nulmer-student — APPROVED** [review]

**Pull request merged**
